# Generated by Django 5.1.2 on 2024-10-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(default='Not Rated', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('horror', 'horror'), ('comedy', 'comedy'), ('sciencefiction', 'sciencefiction'), ('adult', 'adult'), ('thrilling', 'thrilling'), ('romance', 'romance')], default='horror', max_length=60),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='images/movie-6.png', upload_to='photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movieid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('movieid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
