# Generated by Django 5.1.2 on 2024-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_movie_id_remove_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('sciencefiction', 'Science Fiction'), ('adult', 'Adult'), ('thrilling', 'Thrilling'), ('romance', 'Romance')], default='horror', max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
