# Generated by Django 5.1.2 on 2024-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_category_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('sciencefiction', 'Science Fiction'), ('adult', 'Adult'), ('thrilling', 'Thrilling'), ('romance', 'Romance')], max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
