# Generated by Django 5.1.2 on 2024-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movie_age_limit_alter_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='age_limit',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Hollywood', 'Hollywood'), ('Anime', 'Anime')], max_length=50),
        ),
    ]
