# Generated by Django 5.1.2 on 2024-10-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_movie_age_limit_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
