# Generated by Django 5.2.1 on 2025-05-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
