# Generated by Django 5.2.1 on 2025-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Hollywood', 'Hollywood'), ('Anime', 'Anime'), ('Action', 'Action')], max_length=50),
        ),
    ]
