# Generated by Django 5.2.1 on 2025-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_movie_category_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
